### ISSUE TITLE
radio channel menu

### ISSUE THREAD

**Issue by ghost** [PeWe79/box-azuracast-player#1]
Hello, your player is one of the best, simple and clear. However, I’ve encountered a problem:
I need to temporarily disable Spotify, 
remove the time and track progress bar from the broadcast, 
and most importantly, move the radio channel menu (the down arrow) to the bottom right. 

On mobile devices, it’s very inconvenient to reach up with a finger.

How can I do this? Can you help me?

**Comment by PeWe79** [comment]
Hi @rfmcom, sorry for late reply. You can add comment `document.getElementById("spotify").href = stream;` on `script.js` and also spotify button on index.html. Also if yo want to remove time track you can add comment on seek-control on index.html and find about seek control on `script.js`.
